polish_words = [
    "abstrakcja", "adaptacja", "adwokat", "akceptacja", "akumulacja", "aktywność", "alergia", "amator", "analiza",
    "anulować", "aparat", "apetyt", "aromat", "artysta", "aspekt", "atakować", "atmosfera", "atrakcja", "autorytet",
    "awaria", "badanie", "bajka", "balansować", "balon", "banan", "bankier", "bariera", "bawić", "bezpieczeństwo",
    "biegać", "biologia", "biuro", "bliskość", "blokować", "bohater", "bomba", "budować", "bufor", "być", "cecha",
    "celebra", "ceremonia", "chcieć", "chemia", "chleb", "chodnik", "chować", "chwila", "cyfra", "czytać", "czas",
    "czasopismo", "częstość", "czynnik", "czystość", "dach", "dane", "darować", "data", "decyzja", "demonstracja",
    "denerwować", "dieta", "doba", "dochód", "doczekać", "dokonanie", "doświadczenie", "drukować", "droga", "drużyna",
    "duma", "dusić", "dynamika", "dyrektor", "działać", "działanie", "dziedzina", "dzieło", "dzień", "dźwięk", "efekt",
    "egzamin", "ekologia", "ekspert", "ekstaza", "ekstrakt", "element", "emisja", "energia", "entuzjazm", "epizod",
    "epoka", "estetyka", "etap", "etykieta", "ewolucja", "fakt", "fantazja", "fascynacja", "festiwal", "figura",
    "filozofia", "filtr", "firma", "flota", "fobia", "fotel", "fotografia", "frakcja", "fragment", "fundacja",
    "fundusz", "funkcja", "futro", "gabinet", "galeria", "gazeta", "genetyka", "geometria", "głośnik", "gotować",
    "grupa", "gryźć", "grunt", "harmonia", "historia", "hodowla", "hotel", "idea", "identyfikacja", "ignorować",
    "ikonografia", "ilość", "ilustracja", "impreza", "indeks", "informacja", "inicjatywa", "instalacja", "instrukcja",
    "intensywność", "interes", "interpretacja", "intymność", "intuicja", "inwencja", "inwestycja", "izolacja", "jakość",
    "jaskinia", "jazda", "jedzenie", "język", "jeździć", "jogurt", "jubileusz", "judaizm", "juhas", "kalendarz",
    "kamera", "kampania", "kanał", "kapitan", "kapsuła", "kariera", "karta", "kategoria", "kawiarnia", "kelner",
    "kierunek", "kilometr", "kino", "klasa", "klimatyzacja", "klub", "kolekcja", "komentarz", "kominek", "komunikacja",
    "komputer", "koncentracja", "koncert", "kondycja", "konferencja", "konkurs", "konsola", "konstrukcja", "kontakt",
    "kontrola", "konwencja", "kończyć", "kooperacja", "korekta", "kosmos", "kosztować", "kot", "krajobraz", "kreatywność",
    "kredyt", "krew", "królestwo", "krytyka", "krzyż", "księżyc", "księgarnia", "kultura", "kuracja", "kurs", "kuszenie",
    "lampa", "landscape", "legenda", "lekarstwo", "lekcja", "lesbijka", "liczba", "lider", "literatura", "lizak", "logika",
    "lubić", "magazyn", "magia", "magister", "makijaż", "mama", "manifestacja", "manipulacja", "mapa", "maraton",
    "matematyka", "materiał", "matka", "mechanizm", "medal", "medycyna", "melodia", "membrana", "miara", "miasto",
    "miłość", "mistrz", "mieszkać", "mieszkanie", "mięso", "miliard", "minister", "misja", "moda", "model", "modlitwa",
    "moduł", "moment", "monitor", "monografia", "morderstwo", "most", "motywacja", "mowa", "mózg", "muzyka", "mysz",
    "nagroda", "napięcie", "narkotyk", "naród", "nauczać", "nauka", "nawigacja", "neuron", "niebo", "niechęć", "niedziela",
    "niespodzianka", "nośnik", "nuda", "numer", "obiad", "obiekt", "obliczać", "obraz", "obszar", "ocena", "odczucie",
    "odkrycie", "ogłoszenie", "ognisko", "oko", "okres", "olej", "organizacja", "orzeł", "osiągnąć", "osoba", "otoczenie",
    "owoc", "paczka", "padaczka", "pamięć", "papier", "parada", "parasol", "parować", "pasja", "pasje", "patrzeć",
    "paznokieć", "pchać", "pełnia", "perfumy", "pianino", "piasek", "piekarnia", "pieniądz", "pierścień", "piękno",
    "pies", "pijaństwo", "pilot", "piosenka", "pisanie", "planeta", "pipczeć", "planować", "plastik", "plecak", "plomba", "pluton",
    "podatek", "podjąć", "podłoga", "podróż", "poemat", "pogoda", "pokazywać", "policja", "pomysł", "pomyłka", "popularność",
    "poranek", "porządek", "postawa", "potrzeba", "powieść", "powinność", "pożar", "pracować", "prawo", "premia", "przyjaźń",
    "przyjęcie", "przyroda", "przyszłość", "pszczoła", "publikacja", "punkt", "pułapka", "pytanie", "rabować", "radar",
    "radość", "radio", "rakieta", "ramię", "ranga", "reagować", "reakcja", "realność", "recepta", "recykling", "redukcja",
    "reguła", "rehabilitacja", "rejestr", "relacja", "religia", "remont", "reprezentacja", "rezultat", "robota", "rola",
    "romans", "rower", "rozmowa", "rozumieć", "ruch", "rzecz", "rynek", "ryzyko", "samochód", "samolot", "satysfakcja",
    "sceptycyzm", "sfera", "siła", "siostra", "sklep", "skorupa", "skrajność", "skryty", "słowo", "słuchawka", "smakować",
    "smutek", "socjalizm", "soczewka", "solidarność", "spadek", "spać", "spinka", "społeczeństwo", "sposób", "sprawa",
    "sprawiedliwość", "sprzedaż", "sprzęt", "spotkanie", "sport", "spożycie", "stać", "stacja", "stan", "stare", "staw",
    "stempel", "stereotyp", "stopień", "stres", "strona", "sukces", "supermarket", "szansa", "szef", "szkoła", "sztuka",
    "szum", "świat", "światło", "świadomość", "tajemnica", "taniec", "tapeta", "telefon", "telewizja", "temperatura",
    "teoria", "tkanina", "tłum", "tolerancja", "towar", "tradycja", "trawa", "trener", "trofeum", "troska", "tuba", "turysta",
    "uczucie", "umysł", "używać", "utopia", "uwaga", "uzależnienie", "walizka", "warga", "warstwa", "wąż", "ważny", "wędrować",
    "wejście", "wędrowiec", "węgiel", "wiedza", "wiek", "więzienie", "wiersz", "wiatr", "wiadomość", "wiedzieć", "wigilia",
    "wilgoć", "wina", "wirus", "witaj", "władza", "wódka", "wojna", "wolność", "wspomnienie", "współpraca", "wstawiać",
    "wszystko", "wulkan", "wybór", "wychodzić", "wydarzenie", "wydawnictwo", "wyjaśniać", "wyjątek", "wyprawa", "wypowiedź",
    "wysiłek", "wyścig", "wystawa", "wytrzymałość", "wywiad", "wzór", "zacząć", "zagadka", "zagranica", "zajmować",
    "zakład", "zaleta", "zamykać", "zapał", "zapach", "zapisywać", "zasada", "zasób", "zawartość", "zdanie", "zdarzenie",
    "zdjęcie", "zdrowie", "zdumiewać", "zdziwienie", "zegar", "zespół", "zgoda", "ziemia", "zima", "zjawisko", "zmiana",
    "zmniejszać", "znaczenie", "znaleźć", "znieść", "znosić", "zrozumienie", "zysk", "życie", "żywioł", "żywność", "żyć",
    "żywotność", "żaba", "żart", "żeglować", "żołądek", "żołnierz", "żona", "żółw", "żuraw", "żyrandol"
]
